### ISSUE TITLE
Fails to parse generics without a trailing comma

### ISSUE THREAD

**Issue by gtm-nayan** [TyrealHu/acorn-typescript#27]
`const a: Foo<T,> = 1` will succeed however `const a: Foo<T> = 1` will raise an unexpected token error.

Stack trace
```
SyntaxError: Unexpected token (1:18)
    at pp$4.raise (node_modules/.pnpm/acorn@8.8.2/node_modules/acorn/dist/acorn.mjs:3459:13)
    at A.raiseCommonCheck (node_modules/.pnpm/acorn-typescript@1.2.10_acorn@8.8.2/node_modules/acorn-typescript/lib/index.mjs:4216:38)
    at A.raise (node_modules/.pnpm/acorn-typescript@1.2.10_acorn@8.8.2/node_modules/acorn-typescript/lib/index.mjs:4223:18)
    at pp$9.unexpected (node_modules/.pnpm/acorn@8.8.2/node_modules/acorn/dist/acorn.mjs:760:8)
    at A.tsParseNonArrayType (node_modules/.pnpm/acorn-typescript@1.2.10_acorn@8.8.2/node_modules/acorn-typescript/lib/index.mjs:2073:11)
    at A.tsParseArrayTypeOrHigher (node_modules/.pnpm/acorn-typescript@1.2.10_acorn@8.8.2/node_modules/acorn-typescript/lib/index.mjs:2077:20)
    at node_modules/.pnpm/acorn-typescript@1.2.10_acorn@8.8.2/node_modules/acorn-typescript/lib/index.mjs:2100:18
    at A.tsInAllowConditionalTypesContext (node_modules/.pnpm/acorn-typescript@1.2.10_acorn@8.8.2/node_modules/acorn-typescript/lib/index.mjs:1663:14)
    at A.tsParseTypeOperatorOrHigher (node_modules/.pnpm/acorn-typescript@1.2.10_acorn@8.8.2/node_modules/acorn-typescript/lib/index.mjs:2099:14)
    at A.tsParseUnionOrIntersectionType (node_modules/.pnpm/acorn-typescript@1.2.10_acorn@8.8.2/node_modules/acorn-typescript/lib/index.mjs:1798:14) {
  pos: 16,
  loc: Position { line: 1, column: 16 },
  raisedAt: 17

```

**Comment by TyrealHu** [comment]
OK, I gonna handle this issue

**Comment by gtm-nayan** [comment]
Thanks for another quick fix. I see that you've added an error when there is a trailing comma now, but both forms with and without the trailing comma are valid.

**Comment by TyrealHu** [comment]
> Thanks for another quick fix. I see that you've added an error when there is a trailing comma now, but both forms with and without the trailing comma are valid.

https://www.typescriptlang.org/play?ts=5.0.4#code/JYOwLgpgTgZghgYwgAgGIHt0B4AqA+ZAbwF8AoMATwAcUdkBeZEAVwFsAjaUhdEAZzDI4ALjSZcAGmQFGARiA
I test that case. it seems that's not valid while trailing comma an the end of generics

**Comment by gtm-nayan** [comment]
Oh, it seems to depend on where the generic is being used.

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgLhgMRCAPAFQDQD4YC8MAjANwwD0FMYIscANgyAO4CmAJgLABQvAZgFcwwKAEtwMAOZswbAE5jgWbDFwAKAJQwA3pWqNm7bnx4BfXrygBPAA5sUaFfiIAlNlEHywmO22fkVDR08EysnJY8QiLikjJyisAA+vIeXmBaSKgYOPh6QbT0YcaRZkA

But I think it's a compiler error instead of a parser error,
https://ts-ast-viewer.com/#code/MYewdgzgLgBAhgLhgMRCAPAFQDQD4YC8MAjANxA

reports parseDiagnostics as empty

**Comment by TyrealHu** [comment]
acorn-typescript@1.3.1

**Comment by gtm-nayan** [comment]
Great, thanks.
