### ISSUE TITLE
"assert" being treated as reserved word in importdeclarations

### ISSUE THREAD

**Issue by bpstrngr** [TyrealHu/acorn-typescript#45]
Been scratching my head over it for a bit, but then realized it probably originates from the import assertion support (or was that targetting import attributes already? i keep confusing what stands where in that transition). 
parsed file: https://github.com/TooTallNate/proxy-agents/blob/main/packages/https-proxy-agent/src/index.ts#L4
thrown error: 
```
 SyntaxError: Unexpected token (4:7)
    at pp.raise (file:///mnt/chromeos/GoogleDrive/MyDrive/blik/haverbeke_2012_acorn/0/acorn/src/location.js:15:13)
    at TypeScriptParser.raiseCommonCheck (file:///mnt/chromeos/GoogleDrive/MyDrive/blik/tyrealhu_2023_acorn_typescript.js:5169:44)
    at TypeScriptParser.raise (file:///mnt/chromeos/GoogleDrive/MyDrive/blik/tyrealhu_2023_acorn_typescript.js:5175:29)
    at pp.unexpected (file:///mnt/chromeos/GoogleDrive/MyDrive/blik/haverbeke_2012_acorn/0/acorn/src/parseutil.js:111:8)
    at pp.expect (file:///mnt/chromeos/GoogleDrive/MyDrive/blik/haverbeke_2012_acorn/0/acorn/src/parseutil.js:105:26)
    at pp.parseImportSpecifiers (file:///mnt/chromeos/GoogleDrive/MyDrive/blik/haverbeke_2012_acorn/0/acorn/src/statement.js:1063:8)
    at TypeScriptParser.parseImport (file:///mnt/chromeos/GoogleDrive/MyDrive/blik/tyrealhu_2023_acorn_typescript.js:3381:44)
    at pp.parseStatement (file:///mnt/chromeos/GoogleDrive/MyDrive/blik/haverbeke_2012_acorn/0/acorn/src/statement.js:137:44)
    at TypeScriptParser.parseStatement (file:///mnt/chromeos/GoogleDrive/MyDrive/blik/tyrealhu_2023_acorn_typescript.js:3739:30)
    at pp.parseTopLevel (file:///mnt/chromeos/GoogleDrive/MyDrive/blik/haverbeke_2012_acorn/0/acorn/src/statement.js:22:21) {
  pos: 93,
  loc: Position { line: 4, column: 7 },
  raisedAt: 99
}
```

from what i logged, this.type at the "assert" token is tt.name in TypescriptParser.parseImport, but that somehow doesn't equal tt.name in pp.parseImportSpecifiers, with the difference being: 
```
console.log(this.type);
// TokenType { label: 'name', updateContext: null}
console.log(tt.name);
// TokenType { label: 'name', updateContext: [Function (anonymous)]}
```

**Comment by TyrealHu** [comment]
mark version 1.4.8
