### ISSUE TITLE
Unexpected token when using Generic tagged template function

### ISSUE THREAD

**Issue by maastrich** [TyrealHu/acorn-typescript#48]
## Context & Exemple
For some libraries, it is quite usefull to be able to provide the type of a tagged template function

For exemple, `styled-components`:
```tsx
import styled from 'styled-components';

type ExtendedProps = {
    $anyprop: string;
};

const StyledDiv = styled.div<ExtendedProps>`
    color: red;
`;
```

But when using **acorn-typescript** it fails with the error:
```
SyntaxError: Unexpected token (8:43)
    at pp$4.raise (/REDACTED/repro/node_modules/.pnpm/acorn@8.11.2/node_modules/acorn/dist/acorn.js:3571:15)
    at p.raiseCommonCheck (/REDACTED/repro/node_modules/.pnpm/acorn-typescript@1.4.10_acorn@8.11.2/node_modules/acorn-typescript/lib/index.js:1:101327)
    at p.raise (/REDACTED/repro/node_modules/.pnpm/acorn-typescript@1.4.10_acorn@8.11.2/node_modules/acorn-typescript/lib/index.js:1:101481)
    at pp$9.unexpected (/REDACTED/repro/node_modules/.pnpm/acorn@8.11.2/node_modules/acorn/dist/acorn.js:772:10)
    at pp$9.semicolon (/REDACTED/repro/node_modules/.pnpm/acorn@8.11.2/node_modules/acorn/dist/acorn.js:749:68)
    at p.parseVarStatement (/REDACTED/repro/node_modules/.pnpm/acorn-typescript@1.4.10_acorn@8.11.2/node_modules/acorn-typescript/lib/index.js:1:73894)
    at pp$8.parseStatement (/REDACTED/repro/node_modules/.pnpm/acorn@8.11.2/node_modules/acorn/dist/acorn.js:927:19)
    at p.parseStatement (/REDACTED/repro/node_modules/.pnpm/acorn-typescript@1.4.10_acorn@8.11.2/node_modules/acorn-typescript/lib/index.js:1:74861)
    at pp$8.parseTopLevel (/REDACTED/repro/node_modules/.pnpm/acorn@8.11.2/node_modules/acorn/dist/acorn.js:829:23)
    at e.parse (/REDACTED/repro/node_modules/.pnpm/acorn@8.11.2/node_modules/acorn/dist/acorn.js:601:17) {
  pos: 134,
  loc: Position { line: 8, column: 43 },
  raisedAt: 135
}
```

## How to reproduce
> **Note**
> Here is a link for reproduction: https://github.com/maastrich/repro/tree/TyrealHu/acorn-typescript-48

```sh
git clone https://github.com/maastrich/repro.git
cd repro
git switch TyrealHu/acorn-typescript-48
pnpm install
node repro.js
```

**Comment by TyrealHu** [comment]
Its a bug, while parsing tagged template with type. Has been fixed in  acorn-typescript-1.4.11
